# Generated by Django 2.1.9 on 2019-06-24 13:05

import rest_framework_jwt.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('given_name', models.CharField(blank=True, default='', max_length=100)),
                ('family_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', rest_framework_jwt.fields.LowerEmailField(blank=True, help_text='\n            The contact email of the resource.', max_length=254, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, max_length=255, upload_to=rest_framework_jwt.fields.ImageUploadPath())),
                ('app_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
