# Generated by Django 2.1.9 on 2019-06-25 04:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import rest_framework_jwt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=rest_framework_jwt.fields.ImageUploadPath()),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
