# Generated by Django 2.2.3 on 2019-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jwt', '0003_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='family_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
