# Generated by Django 2.2.3 on 2019-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jwt', '0004_auto_20190726_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='\n            The contact email of the resource.', max_length=254),
        ),
    ]
