# Generated by Django 2.2.3 on 2019-07-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jwt', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='rest_framework_jwt.Role'),
        ),
    ]
