# Generated by Django 2.2.3 on 2019-07-28 04:36

from django.db import migrations, models
import rest_framework_jwt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_jwt', '0008_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, upload_to=rest_framework_jwt.fields.UploadPath('image')),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
